import React from "react";
import { Header } from "../../commons/components/Header/Header";
export const HomePage = ()=>{
    return <div>
        <p> 
            admin
        </p>
        <Header />
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
        <p> 
            HomePage
        </p><p> 
            HomePage
        </p>
    </div>
}